#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export PATH="$DIR":$PATH
export LD_PRELOAD=

exec "$DIR/../tmp/gentoo/llvm/bin/clang++"  --config-system-dir="$DIR/../etc/clang" --gcc-install-dir="$DIR/../lib/gcc/<ARCH>/<GCC_VERSION>" --sysroot "$DIR/.." "$@"
