#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export PATH="$DIR":$PATH
export LD_PRELOAD=

exec "$DIR/gcc-<GCC_VERSION>" <OLD_ABI> -fuse-ld=lld --sysroot "$DIR/.." "$@"
