#!/usr/bin/env bash

set -e
set -x

LIBDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/../lib" &> /dev/null && pwd )

loader=$LIBDIR/ld-linux-x86-64.so.2

if [ -z "$1" ]; then
    echo "Usage: $0 <program> <perf_file> [perf_signal]"
    exit 1
fi

if [ -z "$2" ]; then
    echo "Usage: $0 <program> <perf_file> [perf_signal]"
    exit 1
fi

if [ -n "$3" ]; then
    num=$3
    if [ ! -z "${num##*[!0-9]*}" ]
    then
        if [ $num -lt 65 ] && [ $num -gt 0 ]
        then
            SIG="CPUPROFILESIGNAL=$3"
        fi
    fi
    if [ -z $SIG ]
    then
        echo "Usage: $0 <program> <perf_file> [perf_signal]"
        echo "perf_signal should be >= 1 and <= 64"
        exit 1
    fi
fi

prog=$(realpath "$1")

exec env LD_LIBRARY_PATH="$LIBDIR" LD_PRELOAD="$LIBDIR/libunwind.so:$LIBDIR/libprofiler.so" CPUPROFILE="$2" $SIG "$loader" --library-path "$LIBDIR" --inhibit-cache "$prog"
